### ISSUE TITLE
PersistentObject issue after upgrading to v0.1.0-SNAPSHOT

### ISSUE THREAD

**Issue by chrismayer** [terrestris/shogun2#160]
After upgrading an existing SHOGun2 project to current master (v0.1.0-SNAPSHOT) I am running into the following issue:
While starting my servlet container (Tomcat v7 in my case) the following exception is thrown while SHOGun tries to init the database content: 
```
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 
'contentInitializer': Injection of resource dependencies failed; nested exception is 
org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 
[de.terrestris.shogun2.model.PersistentObject] found for dependency 
[collection of de.terrestris.shogun2.model.PersistentObject]: expected at least 1 bean which 
qualifies as autowire candidate for this dependency. Dependency annotations: 
{@javax.annotation.Resource(shareable=true, lookup=, name=, description=, 
authenticationType=CONTAINER, type=class java.lang.Object, mappedName=), 
@org.springframework.beans.factory.annotation.Qualifier(value=objectsToCreate)}
```
When I get it right the problem is to inject the 'objectsToCreate' (``private List<PersistentObject> objectsToCreate;``) in ``de.terrestris.shogun2.init.ContentInitializer``. 

I  would be thankful for any hint solving this.

**Comment by marcjansen** [comment]
We'll be looking into this shortly. Stay tuned.

**Comment by chrismayer** [comment]
I have a first hook, what the problem is: 

My {ProjectArtifactId}-context-initialize-beans.xml is out of sync with the data structure expected by ``de.terrestris.shogun2.init.ContentInitializer``.  This one has been created by the SHOGun2-Archetype a while ago and looks a bit different than the one in the current archetype https://github.com/terrestris/shogun2/blob/master/src/shogun2-webapp-archetype/src/main/resources/archetype-resources/src/main/resources/META-INF/spring/__artifactId__-context-initialize-beans.xml

I try to update my {ProjectArtifactId}-context-initialize-beans.xml and will report feedback if this solves the problem.

**Comment by chrismayer** [comment]
Okay finally I got it running again. I had to do the following steps:

- Adapt the existing ``{ProjectArtifactId}-context-initialize-beans.xml`` file (under ``src/main/resources/META-INF/spring/``) according to the new structure as it is defined in the [archetype](https://github.com/terrestris/shogun2/blob/master/src/shogun2-webapp-archetype/src/main/resources/archetype-resources/src/main/resources/META-INF/spring/__artifactId__-context-initialize-beans.xml)
- Adapt the existing ``{ProjectArtifactId}-context.xml`` file (under ``src/main/resources/META-INF/spring/``) according to the new structure as it is defined in the [archetype](https://github.com/terrestris/shogun2/blob/master/src/shogun2-webapp-archetype/src/main/resources/archetype-resources/src/main/resources/META-INF/spring/__artifactId__-context.xml)
- Add the missing ``geoServerNameSpaces.properties`` file to ``src/main/resources/META-INF/``, like the one in the [archetype](https://github.com/terrestris/shogun2/blob/master/src/shogun2-webapp-archetype/src/main/resources/archetype-resources/src/main/resources/META-INF/geoServerNameSpaces.properties)

**Comment by marcjansen** [comment]
Do you think you can come up with a PR that documents this here: https://github.com/terrestris/shogun2/blob/master/RELEASE-NOTES.md ?

That'd be so nice :cookie:

**Comment by chrismayer** [comment]
Sure! I opened a PR, see #161.
