### ISSUE TITLE
Refactoring Trees

### ISSUE THREAD

**Issue by KaiVolland** [terrestris/shogun2#205]
As we allready decided we will redesign or introduce a general tree which can be associated with any persistentobject.

This is a first draft of a tree:

![tree](https://cloud.githubusercontent.com/assets/1849416/16839566/0529f23c-49d0-11e6-9aff-4ca2e2c1ad3b.png)

**Comment by buehner** [comment]
I commited to your branch in #206 
Please have a look at my comment there!
