### ISSUE TITLE
Remove compatibility with Java7 from SHOGun2?

### ISSUE THREAD

**Issue by ahennr** [terrestris/shogun2#288]
Since Java7 is not maintained / updated any longer (since a couple of time), we should think about removing compatibility with Java7 from SHOGun2 in the future.

@terrestris/devs : What do you think?

**Comment by hwbllmnn** [comment]
Sounds good to me! Even Java8 will probably only be supported until ~ end of 2018, so it's definitely time.

**Comment by buehner** [comment]
:+1: we should soon make a last release that still supports Java 7

**Comment by ahennr** [comment]
See discussion in https://github.com/terrestris/shogun2/pull/289

**Comment by buehner** [comment]
As #289 is merged, we don't support Java 7 anymore. So I'll close this issue now.
