### ISSUE TITLE
Refactor `getMostSpecificRule` in `GeoServerInterceptorService`

### ISSUE THREAD

**Issue by KaiVolland** [terrestris/shogun2#311]
The `getMostSpecificRule` method in the  `GeoServerInterceptorService` needs to be refactored as the first rule that matches any of the checks in the `condition` Predicate will be returned as the most specific, even if possible following rules are more specific.

The condition does not compare rules with each other.

**Comment by ahennr** [comment]
See https://github.com/terrestris/shogun2/pull/312 and https://github.com/terrestris/shogun2/pull/313
