### ISSUE TITLE
Authenticated HTTP requests in interceptor

### ISSUE THREAD

**Issue by hwbllmnn** [terrestris/shogun2#315]
Make the Geoserver interceptor capable of simple HTTP Basic authentication.

**Comment by marcjansen** [comment]
When do we have time for this? or have we fixed this in between?

**Comment by hwbllmnn** [comment]
Looks like there is at least some support in the `HttpUtil` that @ahennr implemented years ago: https://github.com/terrestris/shogun2/commit/6ab9a679d0cc6fd954baa0bf1360ea38e4d5ddd2 . I'm unsure if that applies to the interceptor yet, though.

**Comment by buehner** [comment]
I dont think that this applies to the interceptor. I have a smart project-solution which enables the interceptor to use basic auth ("functional user") for all OGC requests. Maybe i'll find the time to make an appropriate pull request soon

**Comment by marcjansen** [comment]
This would be much appreciated.

**Comment by buehner** [comment]
Can this be closed as #330 is merged?

**Comment by hwbllmnn** [comment]
Sure, closing...
