### ISSUE TITLE
data model(ling)

### ISSUE THREAD

**Issue by KaiVolland** [terrestris/shogun2#34]
After todays virtual hangout about the data model I'm going to open this issue so we can share our hangoutresults and thoughts about the data model.

First of all I was searching for a tool to create, collaboratively edit and share UML-Projects. 
Ther are a lot of tools to do these things...
I decided to use [GenMyModel](http://www.genmymodel.com) because I read some positive things about it and it has some export functionalities that might be useful.

Actually everybody who knows the link to this UML-Project can edit the models. So i send a mail to the coders attending to the hangout today.

No we can talk about the data model itself...

**Comment by KaiVolland** [comment]
Maybe we should close this issue, as we just refactored the modelling in the past week.

**Comment by buehner** [comment]
:+1:  I had the same thought!

**Comment by marcjansen** [comment]
We can always reopen if necessary
