### ISSUE TITLE
Login fails after web application setup

### ISSUE THREAD

**Issue by chrismayer** [terrestris/shogun2#89]
I did the steps described in the wiki for setting up a first web application (see https://github.com/terrestris/shogun2/wiki/Getting-started). Everything works fine, the application is running in a tomcat. But if I try to login it fails. Since the wiki says ``You can enter any values here to login to your SHOGun2-based web application`` I wonder if I have to do anything special or if I did something wrong?

**Comment by marcjansen** [comment]
From the top of my head: Earlier versions required user `admin` and any `password` but recent changes may have affected this behaviour.

**Comment by chrismayer** [comment]
Still no success by using user ``admin`` @marcjansen

**Comment by buehner** [comment]
I think the wiki/documentation is outdated and should be updated soon.

It should be possible to login with admin/shogun2

**Comment by chrismayer** [comment]
Fine that works. Thanks @buehner!

**Comment by marcjansen** [comment]
Up for a wiki change @chrismayer ? I'd love to see you here more often :wink:

**Comment by chrismayer** [comment]
Wiki page is corrected @marcjansen. I'll see what I can do hanging around here more often :wink:

**Comment by marcjansen** [comment]
:+1:

**Comment by buehner** [comment]
@marcjansen I pulled the doc changes of the doc/wiki submodule.

This is easily done be executing these commands on the shogun2 root dir:

(0. `git submodule update --init --recursive` if the submodule has not yet been initialized)
1. `git submodule foreach git pull origin master`
2. `git add ...`
3. `git commit`
4. `git push ...`

I will add this to the README

**Comment by marcjansen** [comment]
Thanks!
