### ISSUE TITLE
REST

### ISSUE THREAD

**Issue by KaiVolland** [terrestris/shogun2#90]
- [x] Create REST-Branch
- [x] Create package `de.terrestris.shogun2.rest`
- [x] Create Controller
-  [x] Support at least the CRUD-operations [Basic example](http://websystique.com/springmvc/spring-mvc-4-restful-web-services-crud-example-resttemplate/)
  -  Should be as generic as possible
    -  [x] Detect Task (Create, Read, Update, Delete) by URI and method (GET, POST, PUT, DELETE)
    -  [x] Detect Model

**Comment by buehner** [comment]
Have a look at the official spring guide: https://spring.io/guides/gs/rest-service/

Here are some links to approaches that are very similar to our (generic service) setup:

* http://stackoverflow.com/a/7391863
* http://stackoverflow.com/a/17016957
* https://gist.github.com/wvuong/5673644

Good luck!

**Comment by buehner** [comment]
We should annotate our concrete implementations with `@RestController` !

**Comment by KaiVolland** [comment]
We have to check ACL behaviour:

Would we like to return 403 (comes currently from ACL) or 404 if an object we want to get/update/delete is not existing?

**Comment by KaiVolland** [comment]
The REST-Interface is now available in the rest branch. We should disucss about merging it into the master.

**Comment by KaiVolland** [comment]
EXAMPLE CURLS:

CREATE >>>>>>>>
curl \
    -v \
    -X POST \
    -H "Content-type: application/json" \
    -H "Cookie: JSESSIONID=B61B1DF8A32DC4E4DFA666B123B0255A" \
    -H "Connection: keep-alive" \
    -d @create.json \
    http://localhost:8080/mapmavin/rest/application

UPDATE >>>>>>>>
curl \
    -v \
    -X POST \
    -H "Content-type: application/json" \
    -H "Cookie: JSESSIONID=B61B1DF8A32DC4E4DFA666B123B0255A" \
    -H "Connection: keep-alive" \
    -d @update.json \
    http://localhost:8080/mapmavin/rest/application/57

curl \
    -v \
    -X PUT \
    -H "Content-type: application/json" \
    -H "Cookie: JSESSIONID=B61B1DF8A32DC4E4DFA666B123B0255A" \
    -H "Connection: keep-alive" \
    -d @update.json \
    http://localhost:8080/mapmavin/rest/application/53

DELETE >>>>>>>>
curl \
	-v \
	-X DELETE \
	-H "Cookie: JSESSIONID=B61B1DF8A32DC4E4DFA666B123B0255A" \
	-H "Connection: keep-alive" \
	http://localhost:8080/mapmavin/rest/application/52

delete.json
{
	"name": "Peter sing Applikeyschen",
	"description": "Peter sing Applikeyschen",
	"language": null,
	"open": true,
	"active": true,
	"url": null,
	"viewport": null
}

update.json
{
    "id": 69,
	"name": "Updated peters Application",
	"description": "Updated peters Application",
	"language": null,
	"open": true,
	"active": true,
	"url": null,
	"viewport": null
}

**Comment by buehner** [comment]
I opened a new PR in #96 
Have a look at it, please! :v:

**Comment by marcjansen** [comment]
#96 is nearly good to go. Great work so far. :+1: on getting this in!
