### ISSUE TITLE
Creation of table "user" fails with PostgreSQL

### ISSUE THREAD

**Issue by chrismayer** [terrestris/shogun2#93]
The creation of the database table "user" on startup of the webapp fails with PostgreSQL. The Reason is the fact that "user" is a reserved word in PostgreSQL (see [here](http://www.postgresql.org/docs/9.4/static/sql-keywords-appendix.html)).
To solve this the table name has to be enclosed by double quotes, which can be achieved in javax.persistance by adding an escaped table name declaration to the model, like this 

```java
@Table(name="\"user\"")
```
If you confirm this error and go along with the proposed solution, I'll provide a PR.

**Comment by marcjansen** [comment]
Thanks for the bug-report, @chrismayer. I can live with any solution, but would love to have sth. like e.g. a configurable prefix for tables, possibly in a `.properties`-file.

I don't know if this is doable, but that would make this complete DDL-stuff less error-prone.

**Comment by chrismayer** [comment]
Thanks for your reply @marcjansen. I agree that prefixing the table names is a very common practice to make this DDL stuff less error-prone. It seems that there is a hibernate way of doing this with a custom NamingStrategy implementation, as suggested [here](http://stackoverflow.com/questions/4313095/jpa-hibernate-and-custom-table-prefixes) or shown [here](http://www.petrikainulainen.net/programming/tips-and-tricks/implementing-a-custom-namingstrategy-with-hibernate/).

**Comment by marcjansen** [comment]
Yeah this sounds great. Is there any chance we may at some time support sth. like:

```java
@Table(name="${common_tbl_prefix}user")
```

I'd value @buehner feedback here.

**Comment by marcjansen** [comment]
I am plus one on a custom naming strategy as outlined here: http://www.petrikainulainen.net/programming/tips-and-tricks/implementing-a-custom-namingstrategy-with-hibernate/

Inside that naming startegy we can outo wire a bean containg the configurable prefix.

I want to inherit as much of the parent class as possible.

**Comment by chrismayer** [comment]
I am also fine with a custom naming strategy adding a configurable prefix to the table names.

Anyone else an opinion on that?

**Comment by buehner** [comment]
I like the custom naming strategy approach and could/would give it a try within the next days (or even hours).

What's your opinion regarding the requirements?

As a first solution, i would suggest to implement a strategy that

* generates table names in **plural** like in the example above, but more powerful by respecting some basic rules: http://www.edufind.com/english-grammar/plural-nouns/
* (Optionally) allows the use of a prefix for all table names

**Comment by marcjansen** [comment]
Yeah, sounds good!

**Comment by chrismayer** [comment]
:+1:

**Comment by buehner** [comment]
I implemented a naming strategy based on the example above, but then i realized that something has changed with the intoduction of hibernate 5 (which we are using). It seems that they have split the naming strategy in two parts:

* `org.hibernate.boot.model.naming.ImplicitNamingStrategy` - used whenever a table or column is not explicitly named to determine the name to use
* `org.hibernate.boot.model.naming.PhysicalNamingStrategy` - used to convert a "logical name" (either implicit or explicit) name of a table or column into a physical name (e.g. following corporate naming guidelines)

There is not much documentation regarding this change and i did not yet find a satisfying solution. Here are some links:

* http://stackoverflow.com/q/32165694
* http://stackoverflow.com/q/31358356

I will try to understand everything and solve this within the next days...

**Comment by buehner** [comment]
There is a PR: #100

**Comment by buehner** [comment]
I will close this issue as #100 is merged now...
