### ISSUE TITLE
Property "center" of MapConfig transformed to bytea in PostgreSQL

### ISSUE THREAD

**Issue by chrismayer** [terrestris/shogun2#94]
When setting up SHOGun 2 with PostgreSQL (v9.4) as database I encountered that the property "center" of the MapConfig model is transformed to the field type "bytea" in the database:

![mapconfig-model](https://cloud.githubusercontent.com/assets/1185547/11775829/7d031b70-a242-11e5-9d40-c32da58be05e.PNG)

Is this a wanted behaviour?

**Comment by marcjansen** [comment]
> Is this a wanted behaviour?

It is at least wanted behaviour that we don't actually care about the concrete datatype in any of the databases.

The field has type `Point2D.Double`, which at some point we decided makes sense from a modeling point of view.

Which alternative do you think would be a better choice, as I see the issues with a binary dataype of course (harder debugging, nearly impossible to alter from only the database)?

**Comment by marcjansen** [comment]
Two ideas: Use Hibernates `@Embedded` or create a custom serializer / deserializer, which would turn the center into (for example) WKT Point when storing and would parse that one into a `Point2D.Double` when reading it out.

What does everyone think?

**Comment by chrismayer** [comment]
> the issues with a binary dataype of course (harder debugging, nearly impossible to alter from only the database)

This is the main reason why I stumbled upon this @marcjansen since there is no possibilty to change the view without doing it directly in the DB (at least at the moment).
Once you decide this shouldn't be a problem in the future because there is no need to change the data directly in the DB (later on) the default serialization of Hibernate is OK. If not, I am with @marcjansen. One of his two suggestions should solve the problems. Maybe the ``@Embedded`` way is a bit less work and leaves the transformation to Hibernate instead of soing it by own code.

**Comment by buehner** [comment]
There is a PR that solves the problem by using the `@Embedded` annotation: #106
